pgp.decrypt#PGP Decrypter.inputDirectory = /home/aceuser/pgp-test/output
pgp.decrypt#PGP Decrypter.outputDirectory = /home/aceuser/pgp-test/nput
pgp.decrypt#PGP Decrypter.pgpPolicy = {PGP_Policies}:PGP-RCV-CFG-SERVICE-CONTAINER
pgp.decrypt#HTTP Input.URLSpecifier = /pgp/decrypt
pgp.decrypt#File Read.inputDirectory = /home/aceuser/pgp-test/

pgp.encrypt#PGP Encrypter.inputDirectory = /home/aceuser/pgp-test/input
pgp.encrypt#PGP Encrypter.outputDirectory = /home/aceuser/pgp-test/output
pgp.encrypt#PGP Encrypter.pgpPolicy = {PGP_Policies}:PGP-SDR-CFG-SERVICE-CONTAINER
pgp.encrypt#File Read.inputDirectory = /home/aceuser/pgp-test/